contact_links:
  - name: Help
    url: https://github.com/kaplayjs/kaplay/discussions/new?category=q-a
    about: How to use certain kaplay feature, or how to achieve something with kaplay
  - name: Compiling/Contributing
    url: https://github.com/kaplayjs/kaplay/discussions/new?category=q-a
    about: How to compile kaplay/how to contribute to it
